package asyncqueue

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/liuxiaozhicn/async-queue-go/pkg/core"
	"github.com/liuxiaozhicn/async-queue-go/pkg/logger"
	"github.com/liuxiaozhicn/async-queue-go/pkg/queue"
)

type Info struct {
	Waiting  int64 `json:"waiting"`
	Reserved int64 `json:"reserved"`
	Delayed  int64 `json:"delayed"`
	Timeout  int64 `json:"timeout"`
	Failed   int64 `json:"failed"`
}

type Queue struct {
	driver        queue.Driver
	channel       string
	PopTimeout    time.Duration
	handleTimeout time.Duration
	retrySeconds  []int
	messageTTL    int
	maxAttempts   int // Maximum retry attempts from configuration
	name          string
	logger        logger.Interface
}

// NewAsyncQueue creates a new async queue with a driver.
func NewAsyncQueue(driver queue.Driver, channel string, opts ...QueueOption) (*Queue, error) {
	if driver == nil {
		return nil, errors.New("queue driver cannot be nil")
	}
	if channel == "" {
		return nil, errors.New("channel cannot be empty")
	}

	o := defaultQueueOptions(channel)
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	if o.logger == nil {
		o.logger = logger.Default
	}

	if err := driver.Ping(context.Background()); err != nil {
		return nil, fmt.Errorf("driver ping failed: %w", err)
	}

	return &Queue{
		driver:        driver,
		channel:       channel,
		PopTimeout:    time.Duration(o.popTimeout) * time.Second,
		handleTimeout: time.Duration(o.handleTimeout) * time.Second,
		retrySeconds:  append([]int(nil), o.retrySeconds...),
		messageTTL:    o.messageTTL,
		maxAttempts:   o.maxAttempts,
		name:          o.name,
		logger:        o.logger,
	}, nil
}

func (q *Queue) Close() error {
	return nil
}

func (q *Queue) PushJob(ctx context.Context, job Job, delaySeconds int) (string, error) {
	if job == nil {
		return "", fmt.Errorf("push: job must not be nil")
	}
	data, err := json.Marshal(job)
	if err != nil {
		return "", fmt.Errorf("marshal job: %w", err)
	}
	return q.pushMessage(ctx, &core.Message{
		Payload:     data,
		MaxAttempts: q.maxAttempts,
	}, delaySeconds)
}

func (q *Queue) PushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	return q.pushMessage(ctx, m, delaySeconds)
}

func (q *Queue) pushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	if q == nil || q.driver == nil {
		return "", errors.New("queue is nil")
	}
	if m == nil {
		return "", errors.New("message is nil")
	}

	if m.MaxAttempts <= 0 {
		m.MaxAttempts = 1
	}
	// message_id is always generated by the driver.
	m.ID = ""
	if delaySeconds > 0 {
		m.SetStatus(core.StatusDelayed)
	} else {
		m.SetStatus(core.StatusWaiting)
	}
	err := q.driver.Push(ctx, q.channel, m, delaySeconds, q.messageTTL)
	if err != nil {
		q.logger.Warn(ctx, "[Producer:%s] PUSH|error payload:%s delay:%ds error:%v", q.name, m.Payload, delaySeconds, err)
		return "", err
	}

	q.logger.Info(ctx, "[Producer:%s] PUSH|ID:%s payload:%s delay:%ds maxAttempts:%d", q.name, m.ID, m.Payload, delaySeconds, m.MaxAttempts)
	return m.ID, nil
}

func (q *Queue) Info(ctx context.Context) (Info, error) {
	if q == nil || q.driver == nil {
		return Info{}, errors.New("queue is nil")
	}
	i, err := q.driver.Info(ctx, q.channel)
	if err != nil {
		return Info{}, err
	}
	return Info{Waiting: i.Waiting, Reserved: i.Reserved, Delayed: i.Delayed, Timeout: i.Timeout, Failed: i.Failed}, nil
}

func (q *Queue) Reload(ctx context.Context, queueName string) (int, error) {
	if q == nil || q.driver == nil {
		return 0, errors.New("queue is nil")
	}
	return q.driver.Reload(ctx, q.channel, queueName)
}

func (q *Queue) Flush(ctx context.Context, queueName string) error {
	if q == nil || q.driver == nil {
		return errors.New("queue is nil")
	}
	return q.driver.Flush(ctx, q.channel, queueName)
}

func (q *Queue) GetMessage(ctx context.Context, id string) (*core.Message, error) {
	if q == nil || q.driver == nil {
		return nil, errors.New("queue is nil")
	}
	if id == "" {
		return nil, errors.New("id is empty")
	}
	return q.driver.Get(ctx, q.channel, id)
}

func (q *Queue) CancelByID(ctx context.Context, id string) (bool, error) {
	if q == nil || q.driver == nil {
		return false, errors.New("queue is nil")
	}
	if id == "" {
		return false, errors.New("id is empty")
	}
	return q.driver.Cancel(ctx, q.channel, id)
}
