package asyncqueue

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/liuxiaozhicn/async-queue-go/pkg/core"
	"github.com/liuxiaozhicn/async-queue-go/pkg/logger"
	"github.com/liuxiaozhicn/async-queue-go/pkg/queue"
	"github.com/redis/go-redis/v9"
)

type Info struct {
	Waiting  int64 `json:"waiting"`
	Reserved int64 `json:"reserved"`
	Delayed  int64 `json:"delayed"`
	Timeout  int64 `json:"timeout"`
	Failed   int64 `json:"failed"`
}

type Queue struct {
	client               redis.UniversalClient
	driver               queue.Driver
	timeoutSeconds       int
	handleTimeoutSeconds int
	retrySeconds         []int
	maxAttempts          int // Maximum retry attempts from configuration
	name                 string
	logger               logger.Interface
}

var errMessageCapabilityUnsupported = errors.New("driver does not support message management capability")

// NewAsyncQueue creates a new async queue with external Redis client
func NewAsyncQueue(client redis.UniversalClient, channel string, popTimeout int, handleTimeout int, retrySeconds []int, maxAttempts int, name string, l logger.Interface) (*Queue, error) {
	if client == nil {
		return nil, errors.New("redis client cannot be nil")
	}

	// Test connection
	if err := client.Ping(context.Background()).Err(); err != nil {
		return nil, fmt.Errorf("redis ping failed: %w", err)
	}

	driver := queue.NewRedisDriver(client, channel, popTimeout, handleTimeout, retrySeconds)
	return &Queue{client: client, driver: driver, handleTimeoutSeconds: handleTimeout, retrySeconds: retrySeconds, maxAttempts: maxAttempts, name: name, logger: l}, nil
}

// Close releases queue-local resources.
// It does NOT close the shared Redis client — the caller who created
// the client is responsible for closing it.
func (q *Queue) Close() error {
	return nil
}

func (q *Queue) PushJob(ctx context.Context, job Job, delaySeconds int) (string, error) {
	if job == nil {
		return "", fmt.Errorf("push: job must not be nil")
	}
	data, err := json.Marshal(job)
	if err != nil {
		return "", fmt.Errorf("marshal job: %w", err)
	}
	return q.pushMessage(ctx, &core.Message{
		Payload:     data,
		MaxAttempts: q.maxAttempts,
	}, delaySeconds)
}

func (q *Queue) PushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	return q.pushMessage(ctx, m, delaySeconds)
}

func (q *Queue) pushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	if q == nil || q.driver == nil {
		return "", errors.New("queue is nil")
	}
	if m == nil {
		return "", errors.New("message is nil")
	}

	if m.MaxAttempts <= 0 {
		m.MaxAttempts = 1
	}
	// message_id is always generated by the driver.
	m.ID = ""
	if delaySeconds > 0 {
		m.SetStatus(core.StatusDelayed)
	} else {
		m.SetStatus(core.StatusWaiting)
	}
	err := q.driver.Push(ctx, m, delaySeconds)
	if err != nil {
		q.logger.Warn(ctx, "[Producer:%s] PUSH|error payload:%s delay:%ds error:%v", q.name, m.Payload, delaySeconds, err)
		return "", err
	}

	q.logger.Info(ctx, "[Producer:%s] PUSH|id:%s payload:%s delay:%ds maxAttempts:%d", q.name, m.ID, m.Payload, delaySeconds, m.MaxAttempts)
	return m.ID, nil
}

func (q *Queue) Info(ctx context.Context) (Info, error) {
	if q == nil || q.driver == nil {
		return Info{}, errors.New("queue is nil")
	}
	i, err := q.driver.Info(ctx)
	if err != nil {
		return Info{}, err
	}
	return Info{Waiting: i.Waiting, Reserved: i.Reserved, Delayed: i.Delayed, Timeout: i.Timeout, Failed: i.Failed}, nil
}

func (q *Queue) Reload(ctx context.Context, queueName string) (int, error) {
	if q == nil || q.driver == nil {
		return 0, errors.New("queue is nil")
	}
	return q.driver.Reload(ctx, queueName)
}

// DeleteMessage deletes a specific message from all queues
func (q *Queue) DeleteMessage(ctx context.Context, m *core.Message) error {
	if q == nil || q.driver == nil {
		return errors.New("queue is nil")
	}
	if m == nil {
		return fmt.Errorf("message must not be nil")
	}
	if m.ID == "" {
		return fmt.Errorf("message id is empty")
	}

	err := q.driver.Delete(ctx, m)
	if err != nil {
		return fmt.Errorf("delete message: %w", err)
	}

	return nil
}

// DeleteJob is deprecated for id-based queue flow.
// Use PushJob + DeleteByID instead.
func (q *Queue) DeleteJob(ctx context.Context, job Job) error {
	if job == nil {
		return fmt.Errorf("job must not be nil")
	}
	return fmt.Errorf("delete job requires message id: use PushJob + DeleteByID")
}

func (q *Queue) Flush(ctx context.Context, queueName string) error {
	if q == nil || q.driver == nil {
		return errors.New("queue is nil")
	}
	return q.driver.Flush(ctx, queueName)
}

func (q *Queue) GetMessage(ctx context.Context, id string) (*core.Message, error) {
	if q == nil || q.driver == nil {
		return nil, errors.New("queue is nil")
	}
	if id == "" {
		return nil, errors.New("id is empty")
	}
	reader, ok := q.driver.(queue.MessageReader)
	if !ok {
		return nil, errMessageCapabilityUnsupported
	}
	return reader.GetMessage(ctx, id)
}

func (q *Queue) DeleteByID(ctx context.Context, id string) (bool, error) {
	if q == nil || q.driver == nil {
		return false, errors.New("queue is nil")
	}
	if id == "" {
		return false, errors.New("id is empty")
	}
	writer, ok := q.driver.(queue.MessageWriter)
	if !ok {
		return false, errMessageCapabilityUnsupported
	}
	return writer.DeleteMessage(ctx, id)
}

func (q *Queue) RetryByID(ctx context.Context, id string, delaySeconds int) (bool, error) {
	if q == nil || q.driver == nil {
		return false, errors.New("queue is nil")
	}
	if id == "" {
		return false, errors.New("id is empty")
	}
	writer, ok := q.driver.(queue.MessageWriter)
	if !ok {
		return false, errMessageCapabilityUnsupported
	}
	return writer.RetryMessage(ctx, id, delaySeconds)
}
