package asyncqueue

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/liuxiaozhicn/async-queue-go/pkg/core"
	"github.com/liuxiaozhicn/async-queue-go/pkg/logger"
	"github.com/liuxiaozhicn/async-queue-go/pkg/queue"
)

type Info struct {
	Waiting  int64 `json:"waiting"`
	Reserved int64 `json:"reserved"`
	Delayed  int64 `json:"delayed"`
	Timeout  int64 `json:"timeout"`
	Failed   int64 `json:"failed"`
}

type Queue struct {
	driver        queue.Driver
	channel       string
	PopTimeout    time.Duration
	handleTimeout time.Duration
	retrySeconds  []int
	messageTTL    int
	maxAttempts   int // Maximum retry attempts from configuration
	name          string
	logger        logger.Interface
}

// NewAsyncQueue constructs a queue publisher facade on top of a prepared driver.
//
// channel is the backend key prefix used by the driver (for example waiting/reserved/delayed keys).
// opts override defaults such as retry policy, timeout, max attempts and logger behavior.
//
// The constructor validates basic parameters and proactively pings the driver so startup can fail fast.
func NewAsyncQueue(driver queue.Driver, channel string, opts ...QueueOption) (*Queue, error) {
	if driver == nil {
		return nil, errors.New("queue driver cannot be nil")
	}
	if channel == "" {
		return nil, errors.New("channel cannot be empty")
	}

	o := defaultQueueOptions(channel)
	for _, opt := range opts {
		if opt != nil {
			opt(&o)
		}
	}
	if o.logger == nil {
		o.logger = logger.Default
	}

	if err := driver.Ping(context.Background()); err != nil {
		return nil, fmt.Errorf("driver ping failed: %w", err)
	}

	return &Queue{
		driver:        driver,
		channel:       channel,
		PopTimeout:    time.Duration(o.popTimeout) * time.Second,
		handleTimeout: time.Duration(o.handleTimeout) * time.Second,
		retrySeconds:  append([]int(nil), o.retrySeconds...),
		messageTTL:    o.messageTTL,
		maxAttempts:   o.maxAttempts,
		name:          o.name,
		logger:        o.logger,
	}, nil
}

// Close closes queue resources.
//
// Queue currently does not own external resources (driver lifecycle is managed by caller),
// so this is intentionally a no-op for interface compatibility.
func (q *Queue) Close() error {
	return nil
}

// PushTask marshals a task payload and enqueues it with queue defaults.
//
// max attempts is injected from queue-level configuration. delaySeconds > 0 means delayed delivery.
// Returns generated message ID on success.
func (q *Queue) PushTask(ctx context.Context, task Task, delaySeconds int) (string, error) {
	if task == nil {
		return "", fmt.Errorf("push: task must not be nil")
	}
	data, err := json.Marshal(task)
	if err != nil {
		return "", fmt.Errorf("marshal task: %w", err)
	}
	return q.pushMessage(ctx, &core.Message{
		Payload:     data,
		MaxAttempts: q.maxAttempts,
	}, delaySeconds)
}

// PushMessage enqueues a pre-built message.
//
// Use this when caller needs to control message fields directly (for example custom MaxAttempts).
// Message ID is still generated by the driver layer.
func (q *Queue) PushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	return q.pushMessage(ctx, m, delaySeconds)
}

// pushMessage validates the message and persists it via the driver.
//
// It normalizes MaxAttempts, resets message ID (driver-generated), sets initial status from delay,
// then delegates to Driver.Push with queue-level message TTL.
func (q *Queue) pushMessage(ctx context.Context, m *core.Message, delaySeconds int) (string, error) {
	if q == nil || q.driver == nil {
		return "", errors.New("queue is nil")
	}
	if m == nil {
		return "", errors.New("message is nil")
	}

	if m.MaxAttempts <= 0 {
		m.MaxAttempts = 1
	}
	// message_id is always generated by the driver.
	m.ID = ""
	if delaySeconds > 0 {
		m.SetStatus(core.StatusDelayed)
	} else {
		m.SetStatus(core.StatusWaiting)
	}
	err := q.driver.Push(ctx, q.channel, m, delaySeconds, q.messageTTL)
	if err != nil {
		q.logger.Warn(ctx, "[Producer:%s] PUSH|error payload:%s delay:%ds error:%v", q.name, m.Payload, delaySeconds, err)
		return "", err
	}

	q.logger.Info(ctx, "[Producer:%s] PUSH|ID:%s payload:%s delay:%ds maxAttempts:%d", q.name, m.ID, m.Payload, delaySeconds, m.MaxAttempts)
	return m.ID, nil
}

// Info returns current queue counters from the backend driver.
//
// Counters are backend snapshots and may change immediately after return under concurrent load.
func (q *Queue) Info(ctx context.Context) (Info, error) {
	if q == nil || q.driver == nil {
		return Info{}, errors.New("queue is nil")
	}
	i, err := q.driver.Info(ctx, q.channel)
	if err != nil {
		return Info{}, err
	}
	return Info{Waiting: i.Waiting, Reserved: i.Reserved, Delayed: i.Delayed, Timeout: i.Timeout, Failed: i.Failed}, nil
}

// Reload moves messages from a source bucket back to waiting for redelivery.
//
// queueName is the source bucket name understood by the driver (for example timeout/failed).
// The returned int is the number of moved messages.
func (q *Queue) Reload(ctx context.Context, queueName string) (int, error) {
	if q == nil || q.driver == nil {
		return 0, errors.New("queue is nil")
	}
	return q.driver.Reload(ctx, q.channel, queueName)
}

// Flush clears messages from one source bucket.
//
// queueName is the bucket name (for example timeout/failed/delayed) interpreted by the driver.
func (q *Queue) Flush(ctx context.Context, queueName string) error {
	if q == nil || q.driver == nil {
		return errors.New("queue is nil")
	}
	return q.driver.Flush(ctx, q.channel, queueName)
}

// GetMessage fetches one message by ID from driver storage.
//
// Returns (nil, err) when lookup fails. A missing message is represented by driver-specific error behavior.
func (q *Queue) GetMessage(ctx context.Context, id string) (*core.Message, error) {
	if q == nil || q.driver == nil {
		return nil, errors.New("queue is nil")
	}
	if id == "" {
		return nil, errors.New("id is empty")
	}
	return q.driver.Get(ctx, q.channel, id)
}

// Cancel attempts to cancel one message by ID.
//
// The exact cancelable states are driver-defined (typically delayed only).
// It returns true when the message was canceled, false when not cancelable/not found.
func (q *Queue) Cancel(ctx context.Context, id string) (bool, error) {
	if q == nil || q.driver == nil {
		return false, errors.New("queue is nil")
	}
	if id == "" {
		return false, errors.New("id is empty")
	}
	ok, err := q.driver.Cancel(ctx, q.channel, id)
	if err != nil {
		q.logger.Info(ctx, "[Producer:%s] CANCEL|ID:%s success:false error:%v", q.name, id, err)
		return false, err
	}
	q.logger.Info(ctx, "[Producer:%s] CANCEL|ID:%s success:%t", q.name, id, ok)
	return ok, nil
}
